accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns = [
    path('', views.index,name='index'),
    path('login/', views.logIn,name='login'),
    path('signup/', views.signUp,name='signup'),
    path('logout/', views.logOut,name='logout'),
    path('<slug:username>/', views.profile,name='profile'),
    path('<slug:username>/edit', views.edit,name='edit'),
    path('<slug:username>/store', views.store,name='store'),
    url(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',views.activate_account,name='activate'),
    path('explore', views.explore,name='explore'),
    path('vote',views.vote,name='vote'),
    path('storeElo',views.storeElo,name='storeElo'),
    path('search',views.search,name='search'),
    path('<int:id>/detail',views.detail,name='detail')
]

gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index,name='index'),
]

urlpatterns+=staticfiles_urlpatterns()

templates/partials/_footer.html
<footer class="footer">
    <div class="footer_top">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-8">
                    <div class="footer_widget">
                        <div class="address_details text-center">
                            <h4 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">27/01/2020</h4>
                            <h3 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".4s">Hồ Chí Minh, Việt Nam</h3>
                            <p class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">Luôn luôn lắng nghe, luôn luôn thấu hiểu</p>
                            <a href="/accounts/vote" class="boxed-btn3 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".6s">Đánh giá</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copy-right_text">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <p class="copy_right text-center wow fadeInDown" data-wow-duration="1s" data-wow-delay=".5s">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Thong Nguyen &copy; Copyright <script>document.write(new Date().getFullYear());</script> 
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/partials/_girls_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/"><img width="30em" src="{% static 'img/logo.png' %}" alt="Logo"> AlbumSV</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  

      <ul class="navbar-nav" style="width: 100%;">
          <li class="nav-item active">
            <a class="nav-link" href="/accounts/explore">Khám phá</a>
          </li>
          <li>
            <a class="nav-link active" href="/accounts/vote">Đánh giá</a>
          </li>

          {% if not username %}
            <li class="nav-item active">
                <a class="nav-link" href="/accounts/login">Đăng nhập</a>
            </li>

            <li class="nav-item active">
                <a class="nav-link" href="/accounts/signup">Đăng kí</a>
            </li>
          {% else %}
              <li class="nav-item active dropdown bg-dark text-light">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ username }}
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'accounts:profile' username %}">Profile</a>
                      <a class="dropdown-item" href="/accounts/logout">Đăng xuất</a>
                  </div>
              </li>
          {% endif %}
        


          <li class="nav-item" style="margin-left: 55.5em;">
            <form action="{% url 'accounts:search' %}" method="POST" class="form-inline my-2 my-lg-0">
              {% csrf_token %}
              <input name="search-info" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-danger my-2 my-sm-0" type="submit">Tìm</button>
            </form>
          </li>

      </ul>
    </div>
</nav>

templates/partials/_navbar.html
{% load static %}

<header>
    <div class="header-area ">
        <div id="sticky-header" class="main-header-area">
            <div class="container">
                <div class="header_bottom_border">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-3">
                            <div class="logo">
                                <a href="/">
                                    <img width="30%" src="{% static 'img/logo.png' %}" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-9 col-lg-9">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li class="nav-item"><a href="/accounts/explore">Khám phá</a></li>
                                        <li class="nav-item"><a href="/accounts/vote">Đánh giá</a></li>

                                        {% if not username %}

                                            <li class="nav-item">
                                                <a class="nav-link" href="/accounts/login">Đăng nhập</a>
                                            </li>
                            
                                            <li class="nav-item">
                                                <a class="nav-link" href="/accounts/signup">Đăng kí</a>
                                            </li>
                                        {% else %}
                                            <li class="nav-item dropdown">
                                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                {{ username }}
                                                </a>
                                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                    <a class="dropdown-item text-dark" href="{% url 'accounts:profile' username %}">&nbsp;Profile</a>
                                                    <a class="dropdown-item text-dark" href="/accounts/logout">&nbsp;Đăng xuất</a>
                                                </div>
                                            </li>


                                        {% endif %}

                                        <li>
                                            <form action="{% url 'accounts:search' %}" method="POST">
                                                {% csrf_token %}
                                                <input name="search-info" style="width: 10em; display: inline" placeholder="&#128269; Tìm ảnh" onfocus="this.placeholder = ''" onblur="this.placeholder = '&#128269; Tìm ảnh'" id="name" type="text" class="form-control valid">
                                                <button class="btn btn-danger my-2 my-sm-0" type="submit">Tìm</button>
                                            </form>
                                        </li>

                                        <li class="text-white">

                                            {{ id }}
                                        </li>
                                    </ul>   
                                </nav>
                            </div>
                        </div>
                        
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</header>