accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns = [
    path('', views.index,name='index'),
    path('login/', views.logIn,name='login'),
    path('signup/', views.signUp,name='signup'),
    path('logout/', views.logOut,name='logout'),
    path('<slug:username>/', views.profile,name='profile'),
    path('<slug:username>/edit', views.edit,name='edit'),
    path('<slug:username>/store', views.store,name='store'),
    url(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',views.activate_account,name='activate'),
    path('explore', views.explore,name='explore'),
    path('vote',views.vote,name='vote'),
    path('storeElo',views.storeElo,name='storeElo'),
    path('search',views.search,name='search'),
    path('<int:id>/detail',views.detail,name='detail')
]

gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index,name='index'),
]

urlpatterns+=staticfiles_urlpatterns()

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

# Create your models here.
class Accounts(User):
    # account_id=models.AutoField(primary_key=True)
    elo=models.FloatField(default=1500,validators=[MinValueValidator(1000)])
    image=models.ImageField(default='default.png',blank=True) 
    fbLink=models.URLField(unique=False)  
    instLink=models.URLField(unique=False)
    valid=models.BooleanField(default=False)

    class Meta:
        verbose_name_plural='Accounts'

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Accounts
from django.contrib.auth import authenticate

class UserSignUpForm(UserCreationForm):
    email=forms.EmailField(max_length=100,help_text='required')

    class Meta:
        model=Accounts
        fields=('username','email','password1','password2')

    def clean(self,*args,**kwargs):
        email=self.cleaned_data.get('email')
        email_qs=Accounts.objects.filter(email=email)
        if email_qs.exists(): self.add_error('email','This email has been registered')
        return super(UserSignUpForm,self).clean(*args,**kwargs)

class UserLogInForm(forms.Form):
    username=forms.CharField(label=('Username'),required=True)
    password=forms.CharField(label=('Password'),widget=forms.PasswordInput,required=True)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes,force_text
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from django.urls import reverse
from .forms import UserSignUpForm,UserLogInForm
from .token_generator import account_activation_token
from .models import Accounts
import random
import numpy as np

# Create your views here.
def index(request):
    username=None
    if 'username' in request.session: 
        username=request.session['username']
    context={
        'username': username
    }
    return render(request,'pages/index.html',context)

def logIn(request):
    next=request.GET.get('next')
    form=UserLogInForm(request.POST)
    if form.is_valid():
        username=form.cleaned_data.get('username')
        password=form.cleaned_data.get('password')
        account=authenticate(username=username,password=password)

        if account is not None:
            if account.is_active:
                login(request,account)
                request.session['username']=username
                return redirect('/')
        else:
            messages.error(request,'username or password not correct')
    context={
        'form': form
    }
    return render(request,'accounts/logIn.html',context)


def signUp(request):
    if request.method=='POST':
        form=UserSignUpForm(request.POST)
        if form.is_valid():
            account=form.save(commit=False)
            email=form.cleaned_data.get('email')
            account.is_active=False
            account.save()
            current_site=get_current_site(request)
            email_subject='Activate Your Account'
            message=render_to_string('accounts/activateAccount.html',{
                'user': account,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(account.pk)),
                'token': account_activation_token.make_token(account),
            })
            to_email=form.cleaned_data.get('email')
            email=EmailMessage(email_subject,message,to=[to_email])
            email.send()
            return render(request,'accounts/emailActivation.html')
    else:
        form=UserSignUpForm()
    return render(request,'accounts/signUp.html',{'form': form})


def activate_account(request,uidb64,token):
    try:
        uid=force_bytes(urlsafe_base64_decode(uidb64))
        account=Accounts.objects.get(pk=uid)
    except(TypeError,ValueError,OverflowError,Accounts.DoesNotExist):
        account=None
    if account is not None and account_activation_token.check_token(account,token):
        account.is_active=True
        account.save()
        account.backend='django.contrib.auth.backends.ModelBackend'
        login(request,account)
        return render(request,'accounts/verified.html')
    else:
        return HttpResponse('Activation link is invalid')

def logOut(request):
    request.session.flush()
    logout(request)
    return redirect('/')

def profile(request,username):
    account=get_object_or_404(Accounts,username=username)
    if 'username' in request.session: 
        username=request.session['username']
    context={
        'username': username,
        'account': account
    }

    return render(request,'accounts/profile.html',context)

def edit(request,username):
    account=get_object_or_404(Accounts,username=username)
    if 'username' in request.session: 
        username=request.session['username']
    context={
        'username': username,
        'account': account
    }
    return render(request,'accounts/edit.html',context)

def store(request,username):
    account=get_object_or_404(Accounts,username=username)
    if 'username' in request.session: 
        username=request.session['username']
    context={
        'username': username,
        'account': account
    }

    fbLink=request.POST['fbLink']
    instLink=request.POST['instLink']
    img=request.POST['img']

    account.fbLink=fbLink
    account.instLink=instLink
    account.image=img
    if img=='': account.image='default.png'
    account.save()

    return redirect('/')


##################################################################################

def explore(request):
    username=None
    if 'username' in request.session: username=request.session['username']
    accounts=Accounts.objects.order_by('-elo')[:44]

    context={
        'accounts': accounts,
        'username': username 
    }

    return render(request,'accounts/index.html',context)

def detail(request,id):
    account=Accounts.objects.get(pk=id)
    username=None
    if 'username' in request.session: username=request.session['username']

    context={
        'account': account,
        'username': username
    }

    return render(request,'accounts/detail.html',context)

def vote(request):
    username=None
    if 'username' in request.session: username=request.session['username']
    idList=[]
    for g in Accounts.objects.all(): idList.append(g.id)
    
    valid0=valid1=False

    while not valid0:
        idx0=random.randint(0,len(idList)-1)
        id0=idList[idx0]
        account0=Accounts.objects.get(pk=id0)
        if account0.valid: valid0=True

    idx1=idx0
    while not valid1: 
        while idx1==idx0: idx1=random.randint(0,len(idList)-1)
        id1=idList[idx1]
        account1=Accounts.objects.get(pk=id1)
        if account1.valid: valid1=True
        
    username=None
    if 'username' in request.session: 
        username=request.session['username']

    context={
        'account0': account0,
        'account1': account1,
        'username': username
    }
    return render(request,'accounts/vote.html',context)

def storeElo(request):
    
    id_winner=int(request.POST['id-button'])
    id0=int(request.POST['id-account0'])
    id1=int(request.POST['id-account1'])
    elo0=float(request.POST['elo-account0'])
    elo1=float(request.POST['elo-account1'])

    e1=1/(1+10**((elo0-elo1)/400))
    e0=1/(1+10**((elo1-elo0)/400))
    K=30

    if id_winner==id0:
        elo0=elo0+K*(1-e0)
        elo1=elo1+K*(0-e1)
    else:
        elo0=elo0+K*(0-e0)
        elo1=elo1+K*(1-e1)

    account0=Accounts.objects.get(pk=id0)
    account1=Accounts.objects.get(pk=id1)
    account0.elo=elo0
    account1.elo=elo1
    account0.save()
    account1.save()

    return HttpResponseRedirect(reverse('accounts:vote'))

def getEditDistance(s0,s1):
    size0=len(s0)+1
    size1=len(s1)+1
    matrix=np.zeros((size0,size1))

    for x in range(size0): matrix[x,0]=x
    for y in range(size1): matrix[0,y]=y

    for x in range(1,size0):
        for y in range(1,size1):
            if s0[x-1]==s1[y-1]: matrix[x,y]=min(matrix[x-1,y]+1,matrix[x-1,y-1],matrix[x,y-1]+1)
            else: matrix[x,y]=1+min(matrix[x-1,y],matrix[x-1,y-1],matrix[x,y-1])

    return matrix[x-1,y-1]



def findAccounts(info,fbList,instList):
    result=[]
    disList=[]
    tmp=[]
    for fb in fbList: disList.append((fb,getEditDistance(info,fb)))
    disList.sort(key=lambda x: x[1])
    for ele in disList[:3]: tmp.append(ele[0])

    for i in tmp: 
        mid=Accounts.objects.filter(fbLink=i)
        result+=[x for x in mid]

    result=[]
    disList=[]
    tmp=[]
    for inst in instList: disList.append((inst,getEditDistance(info,inst)))
    disList.sort(key=lambda x: x[1])
    for ele in disList[:3]: tmp.append(ele[0])

    for i in tmp: 
        mid=Accounts.objects.filter(instLink=i)
        result+=[x for x in mid if x not in result]
    return result


def search(request):
    username=None
    if 'username' in request.session: username=request.session['username']
    info=request.POST['search-info']
    accounts=Accounts.objects.all()

    nameList=[x.username for x in accounts]
    fbList=[x.fbLink for x in accounts]
    instList=[x.instLink for x in accounts]

    result=[]

    similarTerms=['facebook','fb','instagram','com','www','http','://']
    for word in similarTerms:
        if word in info:
            result=findAccounts(info,fbList,instList)
            context={
                'result': result,
                'username': username
            }
            return render(request,'accounts/search.html',context)

    
    result=[]
    disList=[]
    tmp=[]
    for name in nameList: disList.append((name,getEditDistance(info,name)))
    disList.sort(key=lambda x: x[1])
    for ele in disList[:3]: tmp.append(ele[0])

    for i in tmp: 
        mid=Accounts.objects.filter(username=i)
        result+=[x for x in mid if x not in result]
    context={
        'result': result,
        'username': username
    }
    return render(request,'accounts/search.html',context)

templates/accounts/activateAccount.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/detail.html
{% extends 'base.html' %}

{% block content %}

{% include 'partials/_girls_navbar.html' %}

<br>
<div class="container">
    <div class="card" style="width: 55%; margin: 0 auto">
        <div class="card-img-top" style="margin-left: 0.5em; margin-top: 0.5em; margin-bottom: 0.5em">
            <a href=""><img src="{{account.image.url}}" style="border: 0.1em solid #6495ED;" width="30em" height="30em" class="rounded-circle" alt="..."></a>
            &nbsp;
            <a href="" class="font-weight-bold">{{account.username}}</a>
        </div>

        <img src="{{account.image.url}}" style="margin: 0 auto" width="100%" height="30%" alt="...">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-1">
                    <b style="color: black; font-size: 0.87em;">Elo</b>
                </div>

                <div class="col-lg-11">
                    {{account.elo}}
                </div>
                
            </div>
            <br>

            <a href="{{account.fbLink}}">
                <div class="row">
                    <div class="col-lg-1">
                        <i class="fa fa-facebook-f"></i>&nbsp;
                    </div>
                
                    <div class="col-lg-11">
                        {{account.fbLink}}
                    </div>
                </div>
            </a>
            <br>
            <a href="{{account.instLink}}">
                <div class="row">
                    <div class="col-lg-1">
                        <i style="font-weight: bold;" class="fa fa-instagram"></i>&nbsp;
                    </div>

                    <div class="col-lg-11">
                        {{account.instLink}}
                    </div>

                </div>
            </a>
        </div>
    </div>

</div>

{% endblock %}

templates/accounts/edit.html
{% extends 'base.html' %}

{% block header %}

{% include 'partials/_girls_navbar.html' %}

{% endblock %}

{% block content %}


<br>
<div class="container">
    <div class="card" style="width: 55%; margin: 0 auto">
        <div class="card-img-top" style="margin-left: 0.5em; margin-top: 0.5em; margin-bottom: 0.5em">
            <a href=""><img src="{{account.image.url}}" style="border: 0.1em solid #6495ED;" width="30em" height="30em" class="rounded-circle" alt="..."></a>
            &nbsp;
            <a href="" class="font-weight-bold">{{account.username}}</a>
        </div>

        <img src="{{account.image.url}}" style="margin: 0 auto" width="100%" height="30%" alt="...">
        <div class="card-body">
            <form action="{% url 'accounts:store' username %}" method="POST" >
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-1">
                        <b style="color: black; font-size: 0.87em;">Elo</b>
                    </div>

                    <div class="col-lg-11">
                        {{account.elo}}
                    </div>
                    
                </div>
                <br>

                <div class="row">
                    <div class="col-lg-1">
                        <i class="fa fa-facebook-f"></i>&nbsp;
                    </div>
                
                    <div class="col-lg-11">
                        <input type="text" name="fbLink" class="form-control" aria-describedby="basic-addon1" placeholder="{{ account.fbLink }}">
                    </div>
                </div>

                </a>
                <br>

                <div class="row">
                    <div class="col-lg-1">
                        <i style="font-weight: bold;" class="fa fa-instagram"></i>&nbsp;
                    </div>

                    <div class="col-lg-11">
                        <input type="text" name="instLink" class="form-control" aria-describedby="basic-addon3" placeholder="{{ account.instLink }}">
                    </div>

                </div>
                <br>
                <div class="row">
                    <div class="col-lg-1">
                        <i style="font-weight: bold;" class="fa fa-image"></i>&nbsp;
                    </div>

                    <div class="col-lg-11">
                        <input type="file" placeholder="default.png" name="img" class="form-control" aria-describedby="basic-addon3">
                    </div>

                </div>

                <br>
                <div class="row">

                    <div class="col-lg-6">
                        <a class="btn btn-danger justify-content-left" href="{% url 'accounts:profile' username %}">Back</a>
                    </div>

                    <div class="col-lg-6">
                        <button type="submit" class="btn btn-primary float-right">Submit</button>
                    </div>
                </div>
            </form>
        </div>

    </div>

</div>

{% endblock %}

templates/accounts/emailActivation.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container">

    <p>Bạn vui lòng check mail để xác nhận đăng ký</p>
    <br>
    <a href="/" class="btn btn-primary">Quay về</a>

</div>

{% endblock %}

templates/accounts/index.html
{% extends 'base.html' %}

{% block header %}
{% include 'partials/_girls_navbar.html' %}
{% endblock %}

{% block content %}

    <br>

    <div class="container">
        <div class="row">
            {% for account in accounts %}

                {% if account.valid %}

                    <div style="margin-bottom: 0.1em; padding: 0.1em" class="col-lg-3">
                        <a href="/accounts/{{ account.id }}/detail">
                            <img style="margin: 0; padding: 0;" width="100%" height="100%" src="{{account.image.url}}" alt="">
                        </a>
                    </div>

                {% endif %}

            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/accounts/logIn.html
{% extends 'base.html' %}

{% block header %}

{% include 'partials/_girls_navbar.html' %}

{% endblock %}

{% block content %}

<style>

label {
    font-size: 1.5em;    
}

input
{
    width: 100%;
    font-size: 1.5em;
}

</style>
<br>
<div class="container">
    <h1 class="text-center">Log In</h1>
    <br>
    <form class="form-group" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="row">
                <div class="col-lg-4">
                    {{ field.label_tag }}
                </div>
            
                <div class="col-lg-8">
                    {{ field }}
                </div>
            

                <br>
                {% for message in messages %}
                    <div class="col-lg-12">
                        <p class="text-danger">{{ message }}</p>
                    </div>
                {% endfor %}
            </div>

        {% endfor %}
        <br>
        <button style="font-size: 1.2em;" type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block header %}

{% include 'partials/_girls_navbar.html' %}

{% endblock %}

{% block content %}


<br>
<div class="container">
    <div class="card" style="width: 55%; margin: 0 auto">
        <div class="card-img-top" style="margin-left: 0.5em; margin-top: 0.5em; margin-bottom: 0.5em">
            <a href=""><img src="{{account.image.url}}" style="border: 0.1em solid #6495ED;" width="30em" height="30em" class="rounded-circle" alt="..."></a>
            &nbsp;
            <a href="" class="font-weight-bold">{{account.username}}</a>
        </div>

        <img src="{{account.image.url}}" style="margin: 0 auto" width="100%" height="30%" alt="...">
        <div class="card-body">
            <div class="row">
                <div class="col-lg-1">
                    <b style="color: black; font-size: 0.87em;">Elo</b>
                </div>

                <div class="col-lg-11">
                    {{account.elo}}
                </div>
                
            </div>
            <br>

            <div class="row">
                <div class="col-lg-1">
                    <i class="fa fa-facebook-f"></i>&nbsp;
                </div>
            
                <div class="col-lg-11">
                    <a href="{{account.fbLink}}">
                        {{account.fbLink}}
                    </a>

                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-lg-1">
                    <i style="font-weight: bold;" class="fa fa-instagram"></i>&nbsp;
                </div>

                <div class="col-lg-11">
                    <a href="{{account.instLink}}">
                        {{account.instLink}}
                    </a>
                </div>

            </div>
            <br>

            <div class="row">
                <div class="col-lg-1">
                    <i style="font-weight: bold;" class="fa fa-check"></i>&nbsp;
                </div>

                <div class="col-lg-11">
                    {% if account.valid %}
                        <p style="font-size: 1em;" class="text-success">Accepted</p>
                    {% else %}
                        <p style="font-size: 1em;" class="text-danger">Unaccepted</p>
                    {% endif %}

                </div>

            </div>

            <br>
            <a style="margin: 0 auto; display: block" href="{% url 'accounts:edit' username %}" class="btn btn-primary">Edit</a>
        </div>

    </div>

</div>

{% endblock %}

templates/accounts/search.html
{% extends 'base.html' %}

{% block content %}

{% include 'partials/_girls_navbar.html' %}
<br>
<div class="container">
    <h2 class="text-center">Kết Quả</h2>
    <br>
    {% for account in result %}
    <div class="card">
        <div class="card-img-top" style="margin-left: 0.5em; margin-top: 0.5em; margin-bottom: 0.5em">
            <div class="row">
                <div class="col-lg-1">
                    <a href="/accounts/{{account.id}}"><img src="{{account.image.url}}" style="border: 0.1em solid #6495ED;" width="70em" height="70em" class="rounded-circle" alt="..."></a>
                </div>
                <div class="col-lg-11">
                    <a href="/accounts/{{account.id}}" class="font-weight-bold">{{account.username}}</a>
                    <br>
                    Elo: {{ account.elo }}
                </div>
            </div>

        </div>

    </div>
    {% endfor %}
</div>

{% endblock %}

templates/accounts/signUp.html
{% extends 'base.html' %}

{% block header %}

{% include 'partials/_girls_navbar.html' %}

{% endblock %}

{% block content %}
<style>

label {
    font-size: 1.5em;    
}

input
{
    width: 100%;
    font-size: 1.5em;
}

</style>


<br>
<div class="container">
    <h1 class="text-center">Sign Up</h1>
    <br><br>

    <form class="form-group" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="row">
                <div class="col-lg-4">
                    {{ field.label_tag }}
                </div>

                <div class="col-lg-8">
                    {{ field }}
                </div>
                

                <br>
                {% for error in field.errors %}
                    <div class="col-lg-12">
                        <p class="text-danger">{{ error }}</p>
                   </div>

                {% endfor %}
            </div>

        {% endfor %}
        <br>
        <button style="font-size: 1.2em;" type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock %}

templates/accounts/verified.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container">

    <p>Tài khoản của bạn đã được xác nhận</p>
    <br>
    <a href="/" class="btn btn-primary">Quay về</a>

</div>

{% endblock %}

templates/accounts/vote.html
{% extends 'base.html' %}

{% block header %}
{% include 'partials/_girls_navbar.html' %}
{% endblock %}

{% block content %}

<br>

<div class="container" style="width: 100%">
    <h1 class="text-center">Ai xinh hơn??</h1>
    <br><br>
    <form action="{% url 'accounts:storeElo' %}" method="post">
        {% csrf_token %}

        <div class="row"> 
            <div class="col-lg-6">
                <button type="submit" value="{{ account0.id }}" name="id-button" style="display: block; border: none; margin: 0 auto; padding: 0">
                    <div class="card submit" style="width: 25em; height: 35.5em;">
                
                        <img src="{{account0.image.url}}" style="margin: 0 auto" width="100%" height="85%" alt="...">
                        <br>
                        <div style="margin: 0 auto">
                            <a href=""><img src="{{account0.image.url}}" style="border: 0.1em solid #6495ED; margin-bottom: 0.5em;" width="35em" height="35em" class="rounded-circle" alt="..."></a>
                            &nbsp;
                            <a href="/accounts/{{ account0.id }}/detail" class="font-weight-bold" style="font-size: 1.5em">{{account0.username}}</a>
                        </div>
                    </div>
                </button>
            </div>

            <div class="col-lg-6">
                <button type="submit" value="{{ account1.id }}" name="id-button" style="display: block; border: none; margin: 0 auto; padding: 0">

                    <div class="card" style="width: 25em; height: 35.5em; margin: 0 auto">
                    

                        <img src="{{account1.image.url}}" style="margin: 0 auto" width="100%" height="85%" alt="...">
                        <br>
                        <div style="margin: 0 auto">
                            <a href=""><img src="{{account1.image.url}}" style="border: 0.1em solid #6495ED; margin-bottom: 0.5em;" width="35em" height="35em" class="rounded-circle" alt="..."></a>
                            &nbsp;
                            <a href="/account1/{{ account1.id }}/detail" class="font-weight-bold" style="font-size: 1.5em">{{account1.username}}</a>
                        </div>
                    </div>
                </button>
            </div>
        </div>
        <input type="text" name="elo-account0" value="{{ account0.elo }}" hidden>
        <input type="text" name="elo-account1" value="{{ account1.elo }}" hidden>
        <input type="text" name="id-account0" value="{{ account0.id }}" hidden>
        <input type="text" name="id-account1" value="{{ account1.id }}" hidden>
    </form>

</div>

{% endblock %}